### ISSUE TITLE
Deploy with wrangler?

### ISSUE THREAD

**Issue by e271828-** [cloudflare/cloudflare-workers-wasm-demo#3] opened 2019-08-03 18:45 UTC
Can you provide an example of deploying this with wrangler? Presumably that's intended to be the future for wasm in workers on Cloudflare. Think it would need to be packaged as webpack.

**Comment by kentonv** [comment] 2019-08-04 19:57
This example predates Wrangler. I'm not sure Wrangler supports C/C++ at present, I think it's focused on Rust, which has a much cleaner Wasm story...

**Comment by e271828-** [comment] 2019-08-04 20:48
OK. Is this a deprecated approach, then? It has a number of issues from a quick test: for example, extremely high variance (50ms-1200ms) on identical inputs. Or is that an intrinsic issue with Web Workers and WASM modules in their current form?

There also appears to be a more serious issue in CF Workers surfaced by this code: works fine under low load, but starts passing requests directly to the backend as rps goes up. This is a surprising and apparently undocumented failure mode for CFW.

**Comment by kentonv** [comment] 2019-08-04 21:31
Hi @e271828-,

First, please note that "Web Workers" and "Cloudflare Workers" are different things. "[Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers)" run in the browser, whereas Cloudflare Workers run on Cloudflare's servers.

> It has a number of issues from a quick test: for example, extremely high variance (50ms-1200ms) on identical inputs.

How are you measuring these times? Is this the round trip time seen by the client? Where is the client located? How are your generating the traffic? Are the images being served from cache, or is every request going to your origin server? Is it possible that it's your origin server, not Cloudflare, that is slowing down?

It's likely that the worker itself is taking roughly the same amount of time for each request, but other parts of request processing are variable.

> works fine under low load, but starts passing requests directly to the backend as rps goes up.

The Worker implemented by the code in this repository always makes a request to the back-end. The worker performs a fetch() to get the image from the back-end, then resizes it, and returns the resized image.

Typically, images will be cached by Cloudflare's cache. If the fetch() in the worker hits cache, then the request will be satisfied there and no request will be made to the origin. Note that caching is a separate feature of Cloudflare not tied to Workers. Any problems you see with caching likely occur whether or not you have a Worker running. If you think caching is not working correctly, please raise a support ticket.

**Comment by kentonv** [comment] 2019-08-04 21:33
Also, regarding "recommended approaches" -- I would _not_ describe this repository as the "recommended approach" at all. This is a little demo that I threw together very early on, before we had any real tooling around WebAssembly. It takes a very bare-bones approach, not even linking in a real memory allocator. Most applications should use modern tooling like Wrangler, wasm-pack, emscripten, etc.

**Comment by e271828-** [comment] 2019-08-05 01:16
(Corrected reference to Workers rather than WW.)

> > It has a number of issues from a quick test: for example, extremely high variance (50ms-1200ms) on identical inputs.
> 
> How are you measuring these times? Is this the round trip time seen by the client? Where is the client located? How are your generating the traffic? Are the images being served from cache, or is every request going to your origin server? Is it possible that it's your origin server, not Cloudflare, that is slowing down?

Total time per image fetch. Measurements are consistent from multiple US datacenter locations. The fetched images do appear to be served from Cloudflare cache according to the headers, and the origin server is Cloudfront in any case.

Measured via:
```
import requests, json

t, e = [], 0
def get() :
    result = requests.get("url")
    t.append(result.elapsed.total_seconds())
    if result.status_code != requests.codes.ok:
      e += 1

for i in range(50):
  get()

print(sum(t) / len(t), min(t), max(t), len(t), e)
```

> > works fine under low load, but starts passing requests directly to the backend as rps goes up.
> 
> The Worker implemented by the code in this repository always makes a request to the back-end. The worker performs a fetch() to get the image from the back-end, then resizes it, and returns the resized image.

To clarify this point, the route is set up with `<host>.domain.com/*` mapping to the Worker script. It should always be connecting to `<image_host>/<path>` for the fetch, but under heavy load it starts to fetch `domain.com/<path>` which produces a 404.

I can't imagine this is intended behavior, so thought I'd mention it.

> Also, regarding "recommended approaches" -- I would not describe this repository as the "recommended approach" at all. This is a little demo that I threw together very early on, before we had any real tooling around WebAssembly.

Perhaps it's worth creating an updated example using Wrangler + Rust, or at least adding a note to this repo :)

**Comment by kentonv** [comment] 2019-08-05 02:40
Have you signed up for workers ($5/month + usage-based fees), or are you using the free version?

**Comment by e271828-** [comment] 2019-08-05 03:47
Yes, this is the paid version. I see in the dashboard that under load both CPU Exceeded and Exception spike at the same time as the 404s start; this does not occur in our test environment.

**Comment by kentonv** [comment] 2019-08-05 16:19
Did you by any chance add `event.passThroughOnException()` to the worker? This would explain why it falls back to origin when it exceeds the CPU limit.

Unfortunately, it is in fact very easy for this worker to exceed the CPU limit. In my tests it could only handle relatively small images. This example code was not intended to be production-quality. The libraries it uses are not optimized for speed; I chose them as libraries that were easy to compile. I wouldn't recommend trying to use this example in a real production service.

It's likely that _all_ of your requests are in fact exceeding the CPU limit, but you don't see errors right away due to a separate known issue: The Workers runtime is lenient with CPU limits for the first several requests, but clamps down after a while if the worker consistently goes over its limit. This can give the impression that the worker is running fine at first, even when it fact it is using more than 50ms per request. After some time, it starts erroring, and continues to do so from then on.

We'd like to fix this bug by instead having the runtime enforce the CPU limits starting with the very first request. Unfortunately, we can't just make this change since it might "break" some low-traffic workers that have appeared to work fine up until now. We're working on a plan to fix the issue without breaking anyone.

But once the issue is fixed, in your case, the effect would be that all requests fail, because all requests are going over 50ms. We are also working on enabling people to pay for extra CPU time, but don't yet have a specific timeline for when that might happen.

If you just want image resizing on the edge, Cloudflare actually has a dedicated feature for that which you might want to check out:

https://blog.cloudflare.com/announcing-cloudflare-image-resizing-simplifying-optimal-image-delivery/

**Comment by e271828-** [comment] 2019-08-05 18:33
> Did you by any chance add `event.passThroughOnException()` to the worker? This would explain why it falls back to origin when it exceeds the CPU limit.

This must be it. We catch all JS exceptions in our logging wrapper, so it didn't occur to me that our JS code would be affecting exception handling outside the context. 

Presumably that line also tells the supervising context what to do? This should really be documented.

> Unfortunately, it is in fact very easy for this worker to exceed the CPU limit. In my tests it could only handle relatively small images. This example code was not intended to be production-quality. The libraries it uses are not optimized for speed; I chose them as libraries that were easy to compile. I wouldn't recommend trying to use this example in a real production service.

Sounds like the sporadically enforced CPU limit is probably the issue. The images we used are 2-50KB, so not very large. We'd like to perform various image manipulations on the fly, not just resizing. The volume of requests is large (500M+/mo), the space of permutations is large, and the execution time is low, so it would make sense to do this at the edge.

> But once the issue is fixed, in your case, the effect would be that all requests fail, because all requests are going over 50ms. We are also working on enabling people to pay for extra CPU time, but don't yet have a specific timeline for when that might happen.

Good to know. This behavior really needs to be clearly documented, since it's very difficult to debug without working at Cloudflare.
 
> If you just want image resizing on the edge, Cloudflare actually has a dedicated feature for that which you might want to check out:

Doesn't address what we'd like to do, unfortunately, and is priced too high for what it is, since there's no "cached [memoized] calls are free" mitigation, if I understand correctly.

**Comment by kentonv** [comment] 2019-08-05 22:22
Thanks for the feedback. We know we have a lot of work to do here.

I've added a note to the readme that this repo shouldn't be used as a template, with links to other options. I'm closing this issue since it's not an action item for this repository, but we'll definitely be working on improving CPU time enforcement and documentation.

@ashleygwilliams @rita3ko FYI

**Closed as completed by kentonv** 2019-08-05 22:22 UTC
